// Generated by CoffeeScript 1.3.3
(function() {
  var Adapter;

  module.exports = Adapter = (function() {
    'use strict';

    var LogLevel, key, lclevels, name, val, _fn, _i, _len, _ref;

    function Adapter() {}

    LogLevel = require('../LogLevel');

    lclevels = {};

    for (key in LogLevel) {
      val = LogLevel[key];
      lclevels[key.toLowerCase()] = val;
    }

    Adapter.prototype.minLevel = LogLevel.ALL;

    Adapter.prototype.maxLevel = LogLevel.OFF;

    _ref = 'fatal error warn info debug trace'.split(' ');
    _fn = function(name) {
      return Adapter.prototype[name] = function() {
        var _ref1;
        if ((this.minLevel >= (_ref1 = lclevels[name]) && _ref1 >= this.maxLevel)) {
          return this["_" + name].apply(this, arguments);
        }
      };
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      _fn(name);
    }

    return Adapter;

  })();

}).call(this);
