// Generated by CoffeeScript 1.3.3
(function() {
  var ConsoleAdapter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = ConsoleAdapter = (function(_super) {

    __extends(ConsoleAdapter, _super);

    'use strict';


    function ConsoleAdapter(_console) {
      if (_console == null) {
        _console = console;
      }
      ConsoleAdapter.__super__.constructor.apply(this, arguments);
      this._fatal = _console.error || _console.log;
      this._error = _console.error || _console.log;
      this._warn = _console.warn || _console.log;
      this._info = _console.info || _console.log;
      this._debug = _console.debug || _console.log;
      this._trace = _console.debug || _console.log;
    }

    ConsoleAdapter.prototype.toString = function() {
      return 'ConsoleAdapter';
    };

    return ConsoleAdapter;

  })(require('./Adapter'));

}).call(this);
