// Generated by CoffeeScript 1.3.3
(function() {
  var TeeAdapter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  module.exports = TeeAdapter = (function(_super) {
    var name, _fn, _i, _len, _ref;

    __extends(TeeAdapter, _super);

    'use strict';


    function TeeAdapter() {
      var adapters;
      adapters = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.adapters = adapters;
      TeeAdapter.__super__.constructor.apply(this, arguments);
      if (arguments.length === 1 && adapters[0] instanceof Array) {
        this.adapters = adapters[0];
      }
    }

    TeeAdapter.prototype.toString = function() {
      return 'TeeAdapter';
    };

    _ref = 'fatal error warn info debug trace'.split(' ');
    _fn = function(name) {
      return TeeAdapter.prototype[name] = function() {
        var adapter, _j, _len1, _ref1;
        _ref1 = this.adapters;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          adapter = _ref1[_j];
          adapter[name].apply(adapter, arguments);
        }
      };
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      _fn(name);
    }

    return TeeAdapter;

  })(require('./Adapter'));

}).call(this);
