// Generated by CoffeeScript 1.3.3
(function() {
  var TeeAdapter,
    __slice = [].slice;

  module.exports = TeeAdapter = (function() {
    'use strict';

    var name, _fn, _i, _len, _ref;

    function TeeAdapter() {
      var adapters;
      adapters = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.adapters = adapters;
      if (arguments.length === 1 && adapters[0] instanceof Array) {
        this.adapters = adapters[0];
      }
    }

    TeeAdapter.prototype.toString = function() {
      return 'TeeAdapter';
    };

    _ref = 'fatal error warn info debug trace'.split(' ');
    _fn = function(name) {
      return TeeAdapter.prototype[name] = function() {
        var adapter, _j, _len1, _ref1;
        _ref1 = this.adapters;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          adapter = _ref1[_j];
          adapter[name].apply(adapter, arguments);
        }
      };
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      _fn(name);
    }

    return TeeAdapter;

  })();

}).call(this);
