// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var combine, isset, levels,
    __slice = [].slice;

  module.exports = levels = {
    Trace: 1,
    Debug: 2,
    Info: 4,
    Warn: 8,
    Error: 16,
    Fatal: 32
  };

  Object.defineProperties(levels, {
    combine: {
      value: combine = function() {
        var lvls;
        lvls = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return lvls.reduce((function(p, c) {
          return p | c;
        }), 0);
      }
    },
    combineLevels: {
      value: function() {
        var levelNames;
        levelNames = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return combine.apply(null, levelNames.map(function(n) {
          return levels[n];
        }));
      }
    },
    isset: {
      value: isset = function(mask, level) {
        return mask & level;
      }
    },
    isLevel: {
      value: function(mask, levelName) {
        return isset(mask, levels[levelName]);
      }
    }
  });

}).call(this);
